service: dataplattform-ingest

custom:
  stage: ${opt:stage, self:provider.stage}
  project: Dataplattform-${self:custom.stage}
  ingest_lambda: ${self:custom.project}-ingest
  slack_ingest_lambda: ${self:custom.project}-slack_ingest
  github_ingest_lambda: ${self:custom.project}-github_ingest
  apikeys:
    slack_ingest: ${ssm:dataplattform_${self:custom.stage}_slack_ingest_apikey}
    github_ingest: ${ssm:dataplattform_${self:custom.stage}_github_ingest_apikey}
    slack_app_ingest: ${ssm:dataplattform_${self:custom.stage}_slack_event_app_ingest_apikey}
    polling_ingest: ${ssm:dataplattform_${self:custom.stage}_polling_ingest_apikey}
    travis_ingest: ${ssm:dataplattform_${self:custom.stage}_travis_ingest_apikey}
  output:
    file: ../integration_tests/ingest.serverless_outputs_${self:custom.stage}.json

provider:
  name: aws
  stage: dev
  region: eu-central-1
  runtime: python3.7
  memorySize: 1024
  timeout: 5
  role: arn:aws:iam::275823250475:role/dataplattform_basic_lambda #TODO set up roles using serverless
  apiKeys:
    - name: ${self:custom.project}-ingest-key
    - name: ${self:custom.project}-slack_ingest-apikey
      value: ${self:custom.apikeys.slack_ingest}
    - name: ${self:custom.project}-github_ingest-apikey
      value: ${self:custom.apikeys.github_ingest}
    - name: ${self:custom.project}-slack_event_app_ingest-apikey
      value: ${self:custom.apikeys.slack_app_ingest}
    - name: ${self:custom.project}-polling_ingest_apikey
      value: ${self:custom.apikeys.polling_ingest}
    - name: ${self:custom.project}-travis_ingest_apikey
      value: ${self:custom.apikeys.travis_ingest}
  usagePlan:
    throttle: #TODO decide on some values
      burstLimit: 200
      rateLimit: 50
  stackTags:
    Project: ${self:custom.project}
  tags:
    Project: ${self:custom.project}


package:
  individually: true
  exclude:
    - "./**"

functions:
  ingest:
    handler: ingest/ingest.handler
    name: ${self:custom.ingest_lambda}
    description: Main ingest lambda
    role: ingestRole
    layers:
      - arn:aws:lambda:eu-central-1:275823250475:layer:Dataplattform-prod-timestamp_random:2
    package:
      include:
        - 'ingest/*.py'
    environment:
      DATAPLATTFORM_RAW_TABLENAME: ${self:custom.project}
    events:
      - http:
          path: dataplattform_ingest/{type}
          method: post
          private: true
  slack_ingest:
    handler: slack_ingest/slack_ingest.handler
    name: ${self:custom.slack_ingest_lambda}
    description: Slack webhook endpoint
    layers:
      - arn:aws:lambda:eu-central-1:275823250475:layer:Dataplattform-prod-slack_signature_validator:1
    package:
      include:
        - 'slack_ingest/*.py'
    environment:
      DATAPLATTFORM_SLACK_SECRET: ${ssm:dataplattform_slack_shared_secret}
      DATAPLATTFORM_INGEST_APIKEY: ${self:custom.apikeys.slack_ingest}
      DATAPLATTFORM_INGEST_URL:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:custom.stage}/dataplattform_ingest/"
    events:
      - http:
          path: slack_ingest
          method: post
          private: false
  github_ingest:
    handler: github_ingest/github_ingest.handler
    name: ${self:custom.github_ingest_lambda}
    description: Github webhook endpoint
    package:
      include:
        - 'github_ingest/*.py'
    environment:
      DATAPLATTFORM_GITHUB_SECRET: ${ssm:dataplattform_github_shared_secret}
      DATAPLATTFORM_INGEST_APIKEY: ${self:custom.apikeys.github_ingest}
      DATAPLATTFORM_INGEST_URL:
        !Join
        - ''
        - - 'https://'
          - !Ref ApiGatewayRestApi
          - '.execute-api.'
          - ${self:provider.region}
          - '.amazonaws.com/'
          - ${self:custom.stage}
          - '/dataplattform_ingest/GithubType'
    events:
      - http:
          path: github_ingest
          method: post
          private: false

resources:
  Resources:
    ingestRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.project}-IngestRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        Policies:
          - PolicyName: ${self:custom.project}-dynamodb-rawtable-writeonly
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                  Resource:
                    - 'Fn::ImportValue': ${self:custom.project}-dynamodb-rawtable-arn
  Outputs:
    IngestURL:
      Description: "Ingest URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:custom.stage}/dataplattform_ingest/"
      Export:
        Name: ${self:custom.project}-ingest-url
    TravisIngestKey:
      Description: "Ingest key for automated integration tests"
      Value: ${self:custom.apikeys.travis_ingest}
      Export:
        Name: ${self:custom.project}-travis-ingest-apikey

plugins:
  - serverless-stack-output
